# Generated by Django 4.1.13 on 2024-07-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0004_cart_conversation_conversationtouser_coursecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conversationtouser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursedomain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursereviewreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gameview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamificationdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prismamigrations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qnareply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='socialhandle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
