# Generated by Django 4.1.13 on 2024-07-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0005_alter_cart_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchhistory',
            table='SearchHistory',
        ),
    ]
